name: deploy-env-variables-on-gh

on:
  push:
    branches: [main]

jobs:
  env-setup-job:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GRAPHQL_API: ${{ secrets.NEXT_PUBLIC_GRAPHQL_API }}
      GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Get files
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Export static files
      run: npm run export
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      
      with:
      BRANCH: gh-pages
      FOLDER: out


